# Generated by Django 3.1.3 on 2021-01-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
