# Generated by Django 3.1.3 on 2021-04-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credents', '0002_credentials_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
